### ISSUE TITLE
18.1 IL2CPP - Failed to draw setting - Il2CppInterop.Runtime.ObjectCollectedException: Object was garbage collected in IL2CPP domain

### ISSUE THREAD

**Issue by p1xel8ted** [BepInEx/BepInEx.ConfigurationManager#79]
![image](https://github.com/BepInEx/BepInEx.ConfigurationManager/assets/10510767/6ecdc3c0-f338-4e2f-ae37-4d487d32651c)

> [Error  :Configuration Manager] Failed to draw setting DebugMode - Il2CppInterop.Runtime.ObjectCollectedException: Object was garbage collected in IL2CPP domain
   at Il2CppInterop.Runtime.InteropTypes.Il2CppObjectBase.get_Pointer() in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/InteropTypes/Il2CppObjectBase.cs:line 32
   at UnityEngine.GUILayoutOption..ctor(Type type, Object value)
   at UnityEngine.GUILayout.MaxWidth(Single maxWidth)
   at ConfigurationManager.ConfigurationManager.DrawSettingName(SettingEntryBase setting) in D:\SVN\BepInEx.ConfigurationManager\ConfigurationManager.Shared\ConfigurationManager.cs:line 645
   at ConfigurationManager.ConfigurationManager.DrawSingleSetting(SettingEntryBase setting) in D:\SVN\BepInEx.ConfigurationManager\ConfigurationManager.Shared\ConfigurationManager.cs:line 624
[Error  :Configuration Manager] Failed to draw setting CorrectFixedUpdateRate - Il2CppInterop.Runtime.ObjectCollectedException: Object was garbage collected in IL2CPP domain
   at Il2CppInterop.Runtime.InteropTypes.Il2CppObjectBase.get_Pointer() in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/InteropTypes/Il2CppObjectBase.cs:line 32
   at UnityEngine.GUILayoutOption..ctor(Type type, Object value)
   at UnityEngine.GUILayout.MaxWidth(Single maxWidth)
   at ConfigurationManager.ConfigurationManager.DrawSettingName(SettingEntryBase setting) in D:\SVN\BepInEx.ConfigurationManager\ConfigurationManager.Shared\ConfigurationManager.cs:line 645
   at ConfigurationManager.ConfigurationManager.DrawSingleSetting(SettingEntryBase setting) in D:\SVN\BepInEx.ConfigurationManager\ConfigurationManager.Shared\ConfigurationManager.cs:line 624

BE 674
Standard setting, not a custom drawer or anything

**Comment by ManlyMarco** [comment]
Currently it only works in some games that have unstripped UnityEngine.IMGUIModule.dll which this appears to not be one of.

**Comment by Uklosk** [comment]
Hi, do you know any example of game this is working?

**Comment by ManlyMarco** [comment]
HoneyCome, RoomGirl, not much else since it needs a separate fix to patch imgui classes back in.

**Comment by BlueRaja** [comment]
> Hi, do you know any example of game this is working?

Deep Rock Galactic: Survivor (which is on PC Gamepass)
