### ISSUE TITLE
Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.MissingMethodException: Method not found: 'Void LayoutedWindow..ctor(WindowFunction, UnityEngine.Rect, UnityEngine.GUIContent, Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppReferenceArray`1<UnityEngine.GUILayoutOption>, UnityEngine.GUIStyle)

### ISSUE THREAD

**Issue by KryptoST** [BepInEx/BepInEx.ConfigurationManager#82]
![image](https://github.com/BepInEx/BepInEx.ConfigurationManager/assets/30755854/5cd65a04-a5bf-4750-a045-54e3c2100dad)
```
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.MissingMethodException: Method not found: 'Void LayoutedWindow..ctor(WindowFunction, UnityEngine.Rect, UnityEngine.GUIContent, Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppReferenceArray`1<UnityEngine.GUILayoutOption>, UnityEngine.GUIStyle)'.
   at UnityEngine.GUILayout.DoWindow(Int32 id, Rect screenRect, WindowFunction func, GUIContent content, GUIStyle style, Il2CppReferenceArray`1 options)
   at ConfigurationManager.ConfigurationManager.OnGUI() in D:\SVN\BepInEx.ConfigurationManager\ConfigurationManager.Shared\ConfigurationManager.cs:line 330
   at Trampoline_VoidThisConfigurationManager.ConfigurationManager+ConfigurationManagerBehaviourOnGUI(IntPtr , Il2CppMethodInfo* )
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.MissingMethodException: Method not found: 'Void LayoutedWindow..ctor(WindowFunction, UnityEngine.Rect, UnityEngine.GUIContent, Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppReferenceArray`1<UnityEngine.GUILayoutOption>, UnityEngine.GUIStyle)'.
   at UnityEngine.GUILayout.DoWindow(Int32 id, Rect screenRect, WindowFunction func, GUIContent content, GUIStyle style, Il2CppReferenceArray`1 options)
   at ConfigurationManager.ConfigurationManager.OnGUI() in D:\SVN\BepInEx.ConfigurationManager\ConfigurationManager.Shared\ConfigurationManager.cs:line 330
   at Trampoline_VoidThisConfigurationManager.ConfigurationManager+ConfigurationManagerBehaviourOnGUI(IntPtr , Il2CppMethodInfo* )
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.MissingMethodException: Method not found: 'Void LayoutedWindow..ctor(WindowFunction, UnityEngine.Rect, UnityEngine.GUIContent, Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppReferenceArray`1<UnityEngine.GUILayoutOption>, UnityEngine.GUIStyle)'.
   at UnityEngine.GUILayout.DoWindow(Int32 id, Rect screenRect, WindowFunction func, GUIContent content, GUIStyle style, Il2CppReferenceArray`1 options)
   at ConfigurationManager.ConfigurationManager.OnGUI() in D:\SVN\BepInEx.ConfigurationManager\ConfigurationManager.Shared\ConfigurationManager.cs:line 330
   at Trampoline_VoidThisConfigurationManager.ConfigurationManager+ConfigurationManagerBehaviourOnGUI(IntPtr , Il2CppMethodInfo* )
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.MissingMethodException: Method not found: 'Void LayoutedWindow..ctor(WindowFunction, UnityEngine.Rect, UnityEngine.GUIContent, Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppReferenceArray`1<UnityEngine.GUILayoutOption>, UnityEngine.GUIStyle)'.
   at UnityEngine.GUILayout.DoWindow(Int32 id, Rect screenRect, WindowFunction func, GUIContent content, GUIStyle style, Il2CppReferenceArray`1 options)
   at ConfigurationManager.ConfigurationManager.OnGUI() in D:\SVN\BepInEx.ConfigurationManager\ConfigurationManager.Shared\ConfigurationManager.cs:line 330
   at Trampoline_VoidThisConfigurationManager.ConfigurationManager+ConfigurationManagerBehaviourOnGUI(IntPtr , Il2CppMethodInfo* )
``` 

[LogOutput.log](https://github.com/BepInEx/BepInEx.ConfigurationManager/files/14154235/LogOutput.log)

**Comment by ManlyMarco** [comment]
See https://github.com/BepInEx/BepInEx.ConfigurationManager/issues/79#issuecomment-1837160218
No plans on fixing it currently.
