### ISSUE TITLE
Config Manager error

### ISSUE THREAD

**Issue by SalmonCN-RH** [BepInEx/BepInEx.ConfigurationManager#95]
When I press F1 while using the IL2CPP 18.3 version Manager, no config content is displayed (as shown in the figure), and the console keeps outputting the same error. How should I solve it? (My English is not very good, so I used a translator)
Log：
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Warning:Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [Configuration Manager 18.3.0]
[Info   :Il2CppInterop] Registered mono type ConfigurationManager.ConfigurationManager+ConfigurationManagerBehaviour in il2cpp domain
[Message:   BepInEx] Chainloader startup complete
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.NotSupportedException: Method unstripping failed
   at ConfigurationManager.Utilities.ImguiUtils.DrawBackground(Rect position, Nullable`1 color, Int32[] corner) in D:\SVN\BepInEx.ConfigurationManager\ConfigurationManager.Shared\Utilities\ImguiUtils.cs:line 53
   at ConfigurationManager.ConfigurationManager.OnGUI() in D:\SVN\BepInEx.ConfigurationManager\ConfigurationManager.Shared\ConfigurationManager.cs:line 330
   at Trampoline_VoidThisConfigurationManager.ConfigurationManager+ConfigurationManagerBehaviourOnGUI(IntPtr , Il2CppMethodInfo* )
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.NotSupportedException: Method unstripping failed
   at ConfigurationManager.Utilities.ImguiUtils.DrawBackground(Rect position, Nullable`1 color, Int32[] corner) in D:\SVN\BepInEx.ConfigurationManager\ConfigurationManager.Shared\Utilities\ImguiUtils.cs:line 53
   at ConfigurationManager.ConfigurationManager.OnGUI() in D:\SVN\BepInEx.ConfigurationManager\ConfigurationManager.Shared\ConfigurationManager.cs:line 330
   at Trampoline_VoidThisConfigurationManager.ConfigurationManager+ConfigurationManagerBehaviourOnGUI(IntPtr , Il2CppMethodInfo* )
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.NotSupportedException: Method unstripping failed
   at ConfigurationManager.Utilities.ImguiUtils.DrawBackground(Rect position, Nullable`1 color, Int32[] corner) in D:\SVN\BepInEx.ConfigurationManager\ConfigurationManager.Shared\Utilities\ImguiUtils.cs:line 53
   at ConfigurationManager.ConfigurationManager.OnGUI() in D:\SVN\BepInEx.ConfigurationManager\ConfigurationManager.Shared\ConfigurationManager.cs:line 330
   at Trampoline_VoidThisConfigurationManager.ConfigurationManager+ConfigurationManagerBehaviourOnGUI(IntPtr , Il2CppMethodInfo* )
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.NotSupportedException: Method unstripping failed
   at ConfigurationManager.Utilities.ImguiUtils.DrawBackground(Rect position, Nullable`1 color, Int32[] corner) in D:\SVN\BepInEx.ConfigurationManager\ConfigurationManager.Shared\Utilities\ImguiUtils.cs:line 53
   at ConfigurationManager.ConfigurationManager.OnGUI() in D:\SVN\BepInEx.ConfigurationManager\ConfigurationManager.Shared\ConfigurationManager.cs:line 330
   at Trampoline_VoidThisConfigurationManager.ConfigurationManager+ConfigurationManagerBehaviourOnGUI(IntPtr , Il2CppMethodInfo* )
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.NotSupportedException: Method unstripping failed
   at ConfigurationManager.Utilities.ImguiUtils.DrawBackground(Rect position, Nullable`1 color, Int32[] corner) in D:\SVN\BepInEx.ConfigurationManager\ConfigurationManager.Shared\Utilities\ImguiUtils.cs:line 53
   at ConfigurationManager.ConfigurationManager.OnGUI() in D:\SVN\BepInEx.ConfigurationManager\ConfigurationManager.Shared\ConfigurationManager.cs:line 330
   at Trampoline_VoidThisConfigurationManager.ConfigurationManager+ConfigurationManagerBehaviourOnGUI(IntPtr , Il2CppMethodInfo* )
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.NotSupportedException: Method unstripping failed
   at ConfigurationManager.Utilities.ImguiUtils.DrawBackground(Rect position, Nullable`1 color, Int32[] corner) in D:\SVN\BepInEx.ConfigurationManager\ConfigurationManager.Shared\Utilities\ImguiUtils.cs:line 53
   at ConfigurationManager.ConfigurationManager.OnGUI() in D:\SVN\BepInEx.ConfigurationManager\ConfigurationManager.Shared\ConfigurationManager.cs:line 330
   at Trampoline_VoidThisConfigurationManager.ConfigurationManager+ConfigurationManagerBehaviourOnGUI(IntPtr , Il2CppMethodInfo* )
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.NotSupportedException: Method unstripping failed
   at ConfigurationManager.Utilities.ImguiUtils.DrawBackground(Rect position, Nullable`1 color, Int32[] corner) in D:\SVN\BepInEx.ConfigurationManager\ConfigurationManager.Shared\Utilities\ImguiUtils.cs:line 53
   at ConfigurationManager.ConfigurationManager.OnGUI() in D:\SVN\BepInEx.ConfigurationManager\ConfigurationManager.Shared\ConfigurationManager.cs:line 330
   at Trampoline_VoidThisConfigurationManager.ConfigurationManager+ConfigurationManagerBehaviourOnGUI(IntPtr , Il2CppMethodInfo* )
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.NotSupportedException: Method unstripping failed
   at ConfigurationManager.Utilities.ImguiUtils.DrawBackground(Rect position, Nullable`1 color, Int32[] corner) in D:\SVN\BepInEx.ConfigurationManager\ConfigurationManager.Shared\Utilities\ImguiUtils.cs:line 53
   at ConfigurationManager.ConfigurationManager.OnGUI() in D:\SVN\BepInEx.ConfigurationManager\ConfigurationManager.Shared\ConfigurationManager.cs:line 330
   at Trampoline_VoidThisConfigurationManager.ConfigurationManager+ConfigurationManagerBehaviourOnGUI(IntPtr , Il2CppMethodInfo* )
![a](https://github.com/user-attachments/assets/7b0ae558-754c-4a87-b414-7cd48b1ee547)

**Comment by ManlyMarco** [comment]
See https://github.com/BepInEx/BepInEx.ConfigurationManager?tab=readme-ov-file#known-issues
